### ISSUE TITLE
Is this plugin compatible with ASF v5.5 (using DotNet v8)?

### ISSUE THREAD

**Issue by woctezuma** [Ryzhehvost/Case-Insensitive-ASF#5]
I have seen a few ASF plugins be updated to be compatible with ASF v5.5 (using DotNet v8):
- https://github.com/JustArchiNET/ArchiSteamFarm/releases/tag/5.5.0.5

Namely:
- https://github.com/Citrinate/FreePackages/releases/tag/1.3.0
- https://github.com/Citrinate/BoosterManager/releases/tag/2.6.0
- https://github.com/chr233/ASFEnhance/releases/tag/2.0.3.0

Is the `Case-Insensitive-ASF` plugin already compatible with the upcoming version of ASF?

Related:
- https://github.com/Rudokhvist/Commandless-Redeem/issues/14

**Comment by Rudokhvist** [comment]
No, none of my plugins was updated (or even tested) to .net8. But it's planned, worst case right after ASF based on .net8 hits stable release.

**Comment by Rudokhvist** [comment]
Just checked, and this plugin works ootb on new version, no need to update it.

**Comment by woctezuma** [comment]
Great! 🥳
